// -*- mode: C++; c-file-style: "cc-mode" -*-
//*************************************************************************
// DESCRIPTION: Verilator: WAVETOP WSE backend — host runner emission
//
// Emits runner.py (host control loop) and testbench_data.py.
//
// Code available from: https://verilator.org
//
//*************************************************************************
//
// Copyright 2024 by Wilson Snyder. This program is free software; you
// can redistribute it and/or modify it under the terms of either the GNU
// Lesser General Public License Version 3 or the Perl Artistic License
// Version 2.0.
// SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
//
//*************************************************************************

#include "config_build.h"
#include "verilatedos.h"

#include "V3Global.h"
#include "V3WseEmitHost.h"
#include "V3Error.h"
#include "V3File.h"
#include "V3Os.h"

#include <sstream>
#include <string>

//######################################################################
// V3WseEmitHost static method

void V3WseEmitHost::emit(const WsePeMap& peMap, const WseSpsConfig& sps) {
    UINFO(2, "WSE: Emitting host runner..." << endl);

    const std::string prefix = v3Global.opt.prefix();
    const std::string outDir = v3Global.opt.makeDir() + "/" + prefix + "_wse";

    // Ensure directory exists
    V3Os::createDir(v3Global.opt.makeDir());
    V3Os::createDir(outDir);

    // ================================================================
    // Emit runner.py
    // ================================================================
    {
        const std::string filename = outDir + "/runner.py";
        V3OutFile of(filename, V3OutFormatter::LA_C);

        of.puts("#!/usr/bin/env python3\n");
        of.puts("\"\"\"WAVETOP runner — generated by Verilator WAVETOP backend.\n");
        of.puts("\n");
        of.puts("Controls the SPS simulation on the Cerebras WSE fabric.\n");
        of.puts("Design: " + prefix + "\n");
        of.puts("N_PIPE: " + std::to_string(sps.N_pipe) + "\n");
        of.puts("Mesh: " + std::to_string(peMap.meshWidth) + "x"
                + std::to_string(peMap.meshHeight) + "\n");
        of.puts("\"\"\"\n\n");

        of.puts("import argparse\n");
        of.puts("import sys\n");
        of.puts("import struct\n\n");

        of.puts("# Pipeline constants\n");
        of.puts("N_PIPE = " + std::to_string(sps.N_pipe) + "\n");
        of.puts("MESH_WIDTH = " + std::to_string(peMap.meshWidth) + "\n");
        of.puts("MESH_HEIGHT = " + std::to_string(peMap.meshHeight) + "\n");
        of.puts("CLOCK_COLOR = " + std::to_string(WSE_CLOCK_COLOR) + "\n");
        of.puts("CTRL_COLOR = " + std::to_string(WSE_CTRL_COLOR) + "\n");
        of.puts("DISPLAY_COLOR = " + std::to_string(WSE_DISPLAY_COLOR) + "\n");
        of.puts("SENTINEL = 0xDEADBEEF\n\n");

        of.puts("def main():\n");
        of.puts("    parser = argparse.ArgumentParser(description='WAVETOP WSE runner')\n");
        of.puts("    parser.add_argument('--cmaddr', default=None, help='CS address')\n");
        of.puts("    parser.add_argument('--cycles', type=int, default=1000, "
                "help='Simulation cycles')\n");
        of.puts("    parser.add_argument('--compare', default=None, "
                "help='Golden CSV for differential test')\n");
        of.puts("    args = parser.parse_args()\n\n");

        of.puts("    sim_cycles = args.cycles\n\n");

        of.puts("    # 1. Initialize\n");
        of.puts("    try:\n");
        of.puts("        from cerebras.sdk.runtime.sdkruntimepybind import SdkRuntime\n");
        of.puts("        runner = SdkRuntime('" + outDir + "', cmaddr=args.cmaddr)\n");
        of.puts("        runner.load()\n");
        of.puts("        runner.run()\n");
        of.puts("    except ImportError:\n");
        of.puts("        print('WSE: Cerebras SDK not found. Running in dry-run mode.')\n");
        of.puts("        print(f'WSE: Would simulate {sim_cycles} cycles with N_PIPE={N_PIPE}')\n");
        of.puts("        print(f'WSE: Mesh={MESH_WIDTH}x{MESH_HEIGHT}')\n");
        of.puts("        sys.exit(0)\n\n");

        of.puts("    outputs = []\n\n");

        of.puts("    # 2. Pipeline fill\n");
        of.puts("    for slot in range(N_PIPE):\n");
        of.puts("        runner.memcpy_h2d(CLOCK_COLOR, [slot], 0, 0, 1, 1, 4, "
                "streaming=True)\n\n");

        of.puts("    # 3. Main simulation loop\n");
        of.puts("    for rtl_cycle in range(sim_cycles):\n");
        of.puts("        slot = rtl_cycle % N_PIPE\n");
        of.puts("        # Send clock wavelet for next pipeline slot\n");
        of.puts("        runner.memcpy_h2d(CLOCK_COLOR,\n");
        of.puts("                          [(rtl_cycle + N_PIPE) % N_PIPE],\n");
        of.puts("                          0, 0, 1, 1, 4, streaming=True)\n\n");
        of.puts("        # Collect outputs from completed slot\n");
        of.puts("        if rtl_cycle >= N_PIPE:\n");
        of.puts("            done_slot = (rtl_cycle - N_PIPE) % N_PIPE\n");
        of.puts("            out_data = runner.memcpy_d2h(DISPLAY_COLOR,\n");
        of.puts("                                        0, MESH_HEIGHT - 1, 1, 1, 4)\n");
        of.puts("            outputs.append(out_data)\n\n");

        of.puts("            # Check for $finish sentinel\n");
        of.puts("            if out_data and out_data[0] == SENTINEL:\n");
        of.puts("                print(f'WSE: $finish detected at cycle {rtl_cycle - N_PIPE}')\n");
        of.puts("                break\n\n");

        of.puts("    # 4. Drain remaining in-flight cycles\n");
        of.puts("    for i in range(N_PIPE):\n");
        of.puts("        out_data = runner.memcpy_d2h(DISPLAY_COLOR,\n");
        of.puts("                                    0, MESH_HEIGHT - 1, 1, 1, 4)\n");
        of.puts("        outputs.append(out_data)\n\n");

        of.puts("    runner.stop()\n\n");

        of.puts("    # 5. Differential comparison\n");
        of.puts("    if args.compare:\n");
        of.puts("        import csv\n");
        of.puts("        with open(args.compare, 'r') as f:\n");
        of.puts("            reader = csv.reader(f)\n");
        of.puts("            golden = list(reader)\n");
        of.puts("        mismatches = 0\n");
        of.puts("        for i, (got, expected) in enumerate(zip(outputs, golden)):\n");
        of.puts("            if str(got) != str(expected):\n");
        of.puts("                print(f'WSE: MISMATCH at cycle {i}: "
                "got={got} expected={expected}')\n");
        of.puts("                mismatches += 1\n");
        of.puts("                if mismatches > 10:\n");
        of.puts("                    print('WSE: Too many mismatches, stopping.')\n");
        of.puts("                    break\n");
        of.puts("        if mismatches == 0:\n");
        of.puts("            print(f'WSE: All {len(outputs)} cycles match.')\n");
        of.puts("        else:\n");
        of.puts("            print(f'WSE: {mismatches} mismatches found.')\n");
        of.puts("            sys.exit(1)\n\n");

        of.puts("    print(f'WSE: Simulation complete. {len(outputs)} cycles captured.')\n\n");

        of.puts("if __name__ == '__main__':\n");
        of.puts("    main()\n");
    }

    // ================================================================
    // Emit testbench_data.py
    // ================================================================
    {
        const std::string filename = outDir + "/testbench_data.py";
        V3OutFile of(filename, V3OutFormatter::LA_C);

        of.puts("#!/usr/bin/env python3\n");
        of.puts("\"\"\"WAVETOP testbench data — generated by Verilator WAVETOP backend.\n\n");
        of.puts("Contains pre-computed stimulus sequences extracted from Verilog initial blocks.\n");
        of.puts("Design: " + prefix + "\n");
        of.puts("\"\"\"\n\n");

        // TODO: WSE v0.1 — Extract stimulus from $readmemh and initial blocks
        of.puts("# Stimulus data (to be populated from Verilog initial blocks)\n");
        of.puts("# TODO: WSE v0.1 — $readmemh converted to compile-time array initialization\n");
        of.puts("STIMULUS = {}\n\n");

        of.puts("def get_inputs(cycle):\n");
        of.puts("    \"\"\"Return list of (port, value) tuples for the given cycle.\"\"\"\n");
        of.puts("    return STIMULUS.get(cycle, [])\n\n");

        of.puts("def check_outputs(cycle, outputs):\n");
        of.puts("    \"\"\"Check outputs against expected values for the given cycle.\"\"\"\n");
        of.puts("    # TODO: Implement golden reference checking\n");
        of.puts("    pass\n");
    }

    UINFO(2, "WSE: Host runner emission complete." << endl);
}
